name: Backend Lint & Build

on: [push, pull_request]

jobs:
  lint-and-build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Java and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkstyle Lint
        run: mvn checkstyle:check

      - name: Build with Maven
        run: mvn clean compile
